### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by vinayakumarr** [andreykurenkov/emailinsight#1]
Could you please explain briefly about 
1. how to run your code
2. probably you can add sample data set or you can give brief explanation about adding customized data set

**Comment by andreykurenkov** [comment]
hey,
I updated the README with a bit of an explanation. I may document this more in the future, but for now it's really just a set of scripts that can primarily be used by just reading through them and seeing what's in there to understand how to use it.

**Comment by vinayakumarr** [comment]
could you please tell the data format for input data set

**Comment by andreykurenkov** [comment]
Its the .mbox format, which you get after exporting your emails from gmail
for instance
